# Generated by Django 4.1 on 2022-08-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=100)),
                ('am', models.TextField()),
            ],
            options={
                'db_table': 'words',
                'managed': True,
            },
        ),
    ]
